export const STORE_COUNTER_INCREMENT = 'STORE_COUNTER_INCREMENT';
export const STORE_ARTICLE_DELETE = 'STORE_ARTICLE_DELETE';
export const STORE_FILTER_SELECT = 'STORE_FILTER_SELECT';
export const STORE_FILTER_RANGE_DATE = 'STORE_FILTER_RANGE_DATE';
export const STORE_FILTER_RESET = 'STORE_FILTER_RESET';
export const STORE_COMMENT_ADD = 'STORE_COMMENT_ADD';
